name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2

      - uses: pdm-project/setup-pdm@main
        name: Setup PDM
        with:
          python-version: ${{ matrix.python-version }}
          enable-pep582: false

      - name: Install Dependencies
        run: pdm install -G test

      - name: Run Tests
        run: pdm run pytest --cov grappler --cov-report=html --cov-report=term

      - uses: actions/upload-artifact@v3
        with:
          name: coverage report
          path: htmlcov

  checks:
    name: Style Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pre-commit/action@v2.0.3

  deploy-docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pdm-project/setup-pdm@main
        name: Setup PDM
        with:
          python-version: "3.10"
          enable-pep582: false

      - name: Install Dependencies
        run: pdm install
      - run: pdm run mkdocs gh-deploy --force
